apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: my-nginx
spec:
  containers:
  - image: brittosj/httpd
    name: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: my-np-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32222
